service:
  name: spotted

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: localhost

custom:
  dynamodb:
    start:
      migrate: true
      seed: true
      port: 8000
    seed:
      travelBands:
        sources:
          - table: travelBands
            sources: [./seeds/travelBands.json]

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          method: get
          path: hello
  listTravelBandActivities:
    handler: src/handlers/handler.listTravelBandActivities
    events:
      - http:
          method: get
          path: travel-bands/{travelBandId}/activities

resources:
  Resources:
    # Spotters model - Users
    SpottersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: spotterId
            AttributeType: S
        KeySchema:
          - AttributeName: spotterId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: spotters
    # Travel band Model
    TravelBandDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: travelBandId
            AttributeType: S
        KeySchema:
          - AttributeName: travelBandId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: travelBands
    #
    ActivitiesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: activityId
            AttributeType: S
        KeySchema:
          - AttributeName: activityId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: activities
    #
    OfficeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: officeId
            AttributeType: S
        KeySchema:
          - AttributeName: officeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: offices
    #
    BookingDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: bookings
